# Generated by Django 6.0.3 on 2026-03-21 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique UPPER_SNAKE_CASE key, e.g. DEFAULT_HOLIDAYS.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must start with an uppercase letter and contain only uppercase letters, digits, and underscores (e.g. DEFAULT_HOLIDAYS).', regex='^[A-Z][A-Z0-9_]*$')])),
                ('label', models.CharField(help_text='Short human-readable name displayed in the UI.', max_length=120)),
                ('value', models.CharField(help_text='Stored value (always a string; cast to the appropriate type when used).', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Longer explanation of what this configuration controls.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
