# Generated by Django 6.0.3 on 2026-03-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_alter_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(blank=True, help_text='Optional programme this project belongs to.', max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Auto-generated as "Programme Name: Project Name". Override if needed.', max_length=405)),
                ('project_code', models.CharField(blank=True, help_text='Project code for recharging. Required to move to In Progress.', max_length=100)),
                ('project_contacts', models.TextField(blank=True, help_text='Comma-separated list of project contact names.')),
                ('finance_contacts', models.TextField(blank=True, help_text='Comma-separated list of finance contact names.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('sub_status', models.CharField(blank=True, help_text='Configurable via Settings > Configurations. Options depend on the current Status.', max_length=100)),
                ('efforts_issued', models.BooleanField(default=False, help_text='Have effort estimates been issued?')),
                ('efforts_issue_commitment_date', models.DateField(blank=True, help_text='Date by which effort estimates are committed to be issued.', null=True)),
                ('next_connect_date', models.DateField(blank=True, help_text='Date of the next scheduled touchpoint.', null=True)),
                ('run_cost_applies', models.BooleanField(default=False, help_text='Does run cost apply to this project?')),
                ('confidence', models.CharField(choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', help_text='Required to move to In Progress.', max_length=10)),
                ('priority', models.CharField(choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', help_text='Required to move to In Progress.', max_length=10)),
                ('tentative_start_date', models.DateField(blank=True, null=True)),
                ('tentative_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team', models.ForeignKey(blank=True, help_text='Primary team responsible for delivery. Required to move to In Progress.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='teams.team')),
                ('collaborators', models.ManyToManyField(blank=True, help_text='Supporting teams. Cannot include the assigned team.', related_name='collaborating_projects', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, default='System', help_text='Name of the person adding the comment.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
