# Generated by Django 6.0.3 on 2026-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, default='Project', help_text='Configurable via Settings → Configurations (PROJECT_TYPES). Defaults: Project, Maintenance, Optimisation, BAU.', max_length=80),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
