# Generated by Django 6.0.3 on 2026-03-22 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_type_projectcomment_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contingency_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contingency as a percentage of the estimate (e.g. 10 for 10%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimate_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effort estimate in person-days.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimate_link',
            field=models.URLField(blank=True, help_text='Link to the estimate document (e.g. SharePoint).'),
        ),
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.CharField(blank=True, help_text='Unique ALL-CAPS identifier, max 30 chars. Suggested format: PROGRAMMENAME_PROJECT. Leave blank to auto-clear (null stored).', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: estimate_days × day_price × (1 + contingency/100). Currency: GBP (£).', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='EstimateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_days', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_days', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('old_contingency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_contingency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_price', models.DecimalField(blank=True, decimal_places=2, help_text='STORY_POINT_PRICE at time of change.', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated total cost at time of change.', max_digits=12, null=True)),
                ('changed_by', models.CharField(blank=True, default='System', max_length=120)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_history', to='projects.project')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_code', models.CharField(blank=True, max_length=100)),
                ('new_code', models.CharField(blank=True, max_length=100)),
                ('changed_by', models.CharField(blank=True, default='System', max_length=120)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_history', to='projects.project')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
