# Generated by Django 6.0.3 on 2026-03-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0001_initial'),
        ('team_members', '0002_alter_teammember_default_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of leave.')),
                ('end_date', models.DateField(help_text='Last day of leave (inclusive).')),
                ('days', models.PositiveSmallIntegerField(editable=False, help_text='Auto-calculated: (end_date − start_date).days + 1.')),
                ('note', models.TextField(blank=True, help_text='System-generated note. Not entered by users via the UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(help_text='Financial year this leave falls within.', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='financial_years.financialyear')),
                ('team_member', models.ForeignKey(help_text='Team member this leave belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='team_members.teammember')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
