# Generated by Django 6.0.3 on 2026-03-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0002_alter_financialyear_end_date'),
        ('leaves', '0001_initial'),
        ('team_members', '0002_alter_teammember_default_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='days',
            field=models.PositiveSmallIntegerField(editable=False, help_text='Auto-calculated working days: calendar days minus weekends and public holidays from the same financial year.'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='financial_years.financialyear'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='team_members.teammember'),
        ),
    ]
