# Generated by Django 6.0.3 on 2026-03-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.PositiveIntegerField(help_text='Auto-assigned sprint number (e.g. 170). Editable.')),
                ('name', models.CharField(help_text='Auto-generated as "Sprint <number>". Override as needed.', max_length=80)),
                ('start_date', models.DateField(help_text='First day of the sprint.')),
                ('end_date', models.DateField(help_text='Last day of the sprint (inclusive).')),
                ('month', models.CharField(blank=True, editable=False, help_text='Month name derived from end_date (e.g. "April").', max_length=20)),
                ('holiday_count', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Number of public holidays within this sprint.')),
                ('working_days', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Working days (Mon–Fri) minus public holidays within this sprint.')),
                ('is_overridden', models.BooleanField(default=False, help_text='True when the user has manually overridden generated values.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(help_text='Financial year this sprint belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='financial_years.financialyear')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('financial_year', 'sprint_number')},
            },
        ),
    ]
