# Generated by Django 6.0.3 on 2026-03-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set automatically from the last sprint end date when sprints are generated. Leave blank on creation.', null=True, unique=True),
        ),
    ]
