# Generated by Django 6.0.3 on 2026-03-28 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0002_alter_financialyear_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2028, 1, 1), unique=True),
            preserve_default=False,
        ),
    ]
