# Generated by Django 6.0.3 on 2026-03-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0004_alter_financialyear_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
