# Generated by Django 6.0.3 on 2026-03-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(help_text='Date of the holiday.')),
                ('note', models.CharField(blank=True, help_text='Short description, e.g. "Christmas Day".', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(help_text='Financial year this holiday belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='financial_years.financialyear')),
            ],
            options={
                'ordering': ['holiday_date'],
                'unique_together': {('financial_year', 'holiday_date')},
            },
        ),
    ]
