# Generated by Django 6.0.3 on 2026-03-22 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0001_initial'),
        ('projects', '0003_project_contingency_pct_project_estimate_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, help_text='Approved budget ceiling in £. Leave blank if not yet set.', max_digits=14, null=True)),
                ('refined_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-year re-forecast. When set, remaining_budget is calculated against this figure instead of budget_allocated.', max_digits=14, null=True)),
                ('estimates', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Snapshot of the project total cost at time of last save.', max_digits=14, null=True)),
                ('remaining_budget', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated remaining budget. Null when no budget is set.', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='financial_years.financialyear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project')),
            ],
            options={
                'ordering': ['project__programme_name', 'project__project_name'],
                'unique_together': {('project', 'financial_year')},
            },
        ),
    ]
