# Generated by Django 6.0.3 on 2026-03-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approved budget ceiling in £. Auto-seeded as £0.00; edit to set real value.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='remaining_budget',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated remaining budget.', max_digits=14, null=True),
        ),
    ]
