# Generated by Django 6.0.3 on 2026-03-21 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('teams', '0003_alter_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('display_name', models.CharField(blank=True, help_text='Auto-generated as "Last Name, First Name". Override if needed.', max_length=165)),
                ('role', models.CharField(choices=[('ENGINEER', 'Engineer'), ('LEAD_ENGINEER', 'Lead Engineer'), ('ARCHITECT', 'Architect')], default='ENGINEER', max_length=20)),
                ('location', models.CharField(choices=[('ONSITE', 'Onsite'), ('OFFSHORE', 'Offshore')], default='ONSITE', max_length=10)),
                ('employee_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CONTRACTOR', 'Contractor')], default='CONTRACTOR', max_length=15)),
                ('start_date', models.DateField(help_text='Date the member joined / became available for planning.')),
                ('end_date', models.DateField(blank=True, help_text='Date the member leaves. Null means currently active.', null=True)),
                ('default_holidays', models.PositiveSmallIntegerField(default=20, help_text='Holiday days per financial year. Defaults to the system DEFAULT_HOLIDAYS config but can be overridden per member.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='team_members', to='skills.skill')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_on', models.DateField(help_text='Effective date of the team change.')),
                ('note', models.TextField(blank=True, help_text='Optional reason for the move.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='team_members.teammember')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ['-moved_on', '-created_at'],
            },
        ),
    ]
