# Generated by Django 6.0.3 on 2026-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='default_holidays',
            field=models.PositiveSmallIntegerField(default=26, help_text='Holiday days per financial year. Defaults to the system DEFAULT_HOLIDAYS config but can be overridden per member.'),
        ),
    ]
