# Generated by Django 6.0.3 on 2026-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
