# Generated by Django 6.0.3 on 2026-03-28 10:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0006_alter_financialyear_end_date'),
        ('projects', '0003_project_contingency_pct_project_estimate_days_and_more'),
        ('sprints', '0001_initial'),
        ('team_members', '0002_alter_teammember_default_holidays'),
        ('teams', '0003_alter_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('allocation_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Acceptable over/under allocation threshold in percent. Default 10 — e.g. £10k budget, £11k allocated is acceptable (10%), £13k is flagged.', max_digits=5)),
                ('scope_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plans', to='financial_years.financialyear')),
            ],
            options={
                'ordering': ['-financial_year__start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_name', models.CharField(blank=True, help_text='e.g. "ENGINEER X (TBC)" when team_member is not yet known.', max_length=100)),
                ('assignment_type', models.CharField(choices=[('ENGINEER', 'Engineer'), ('ARCHITECT', 'Architect'), ('ADHOC', 'Adhoc / BAU'), ('INTERIM', 'Interim replacement')], default='ENGINEER', max_length=10)),
                ('is_interim', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('pause_from_sprint', models.ForeignKey(blank=True, help_text='This engineer pauses work from this sprint onwards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_pauses', to='sprints.sprint')),
                ('replaces_assignment', models.ForeignKey(blank=True, help_text='The original assignment this interim covers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interim_replacements', to='resource_plan.resourceplanassignment')),
                ('resume_at_sprint', models.ForeignKey(blank=True, help_text='This engineer resumes work at this sprint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_resumes', to='sprints.sprint')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plan_assignments', to='team_members.teammember')),
            ],
            options={
                'ordering': ['phase', 'team_member__last_name', 'team_member__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(default='System', max_length=120)),
                ('change_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='resource_plan.resourceplan')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('CAPACITY_EXCEEDED', 'Capacity exceeded'), ('PRIORITY_CLASH', 'Competing equal priorities'), ('OVER_BUDGET', 'Over budget/estimate'), ('UNDER_BUDGET', 'Under budget/estimate'), ('THRESHOLD_BREACH', 'Allocation threshold breached'), ('ENGINEER_LEAVE', 'Engineer has leave in sprint'), ('ENGINEER_UNAVAILABLE', 'Engineer unavailable')], max_length=25)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=10)),
                ('description', models.TextField()),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending user action'), ('SPLIT', 'Capacity split between projects'), ('PUSHED_RIGHT', 'Lower priority pushed right'), ('REPLACED', 'Engineer replaced / interim assigned'), ('PLACEHOLDER', 'Placeholder engineer created'), ('DEPRIORITISED', 'Project deprioritised'), ('DISMISSED', 'Dismissed by user')], default='PENDING', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='resource_plan.resourceplanassignment')),
                ('affected_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_conflicts', to='sprints.sprint')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='resource_plan.resourceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Phase 1', max_length=100)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('dependency_type', models.CharField(blank=True, choices=[('SS', 'Start to Start'), ('FS', 'Finish to Start'), ('FF', 'Finish to Finish')], help_text='Only used when predecessor_phase is set.', max_length=2)),
                ('ramp_pattern', models.CharField(choices=[('FLAT', 'Flat (uniform across sprints)'), ('RAMP_UP', 'Ramp up (gradual increase)'), ('RAMP_DOWN', 'Ramp down (gradual decrease)'), ('RAMP_UP_DOWN', 'Ramp up → Steady → Ramp down'), ('RAMP_UP_STEADY', 'Ramp up → Steady'), ('STEADY_DOWN', 'Steady → Ramp down')], default='FLAT', max_length=20)),
                ('max_days_per_sprint', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on days allocated per sprint for this phase. Null = use global cap (10).', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('notes', models.TextField(blank=True)),
                ('end_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_ends', to='sprints.sprint')),
                ('predecessor_phase', models.ForeignKey(blank=True, help_text='This phase depends on the predecessor phase (cross-project or same).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_phases', to='resource_plan.resourceplanphase')),
                ('start_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_starts', to='sprints.sprint')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='resourceplanassignment',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='resource_plan.resourceplanphase'),
        ),
        migrations.CreateModel(
            name='ResourcePlanProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('ESTIMATE', 'Estimates (total cost)'), ('BUDGET', 'Budget (allocated or refined)'), ('CUSTOM', 'Custom amount')], default='ESTIMATE', max_length=10)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used only when basis = CUSTOM.', max_digits=14, null=True)),
                ('days_required', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='amount ÷ day_rate, rounded to nearest 0.25.', max_digits=8, null=True)),
                ('priority_override', models.CharField(blank=True, choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], help_text='Overrides project.priority for this plan only.', max_length=10)),
                ('confidence_override', models.CharField(blank=True, choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], help_text='Overrides project.confidence for this plan only.', max_length=10)),
                ('dates_strict', models.BooleanField(default=False, help_text='If True, tentative dates cannot be pushed right even when there is a capacity conflict. If False, the engine may right-shift.')),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_projects', to='resource_plan.resourceplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plan_entries', to='projects.project')),
            ],
            options={
                'ordering': ['plan', 'project__programme_name', 'project__project_name'],
                'unique_together': {('plan', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('PERCENT', 'Percentage of project (%)'), ('DAYS', 'Fixed days'), ('BUDGET', 'Budget amount (£)')], default='PERCENT', max_length=10)),
                ('allocation_value', models.DecimalField(decimal_places=2, help_text='Percent (0–100), fixed days, or £ amount depending on allocation_type.', max_digits=10)),
                ('sequence_order', models.PositiveIntegerField(default=1, help_text='Controls the order teams start on this project. Teams with the same sequence_order run in parallel.')),
                ('notes', models.TextField(blank=True)),
                ('plan_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='resource_plan.resourceplanproject')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_plan_teams', to='teams.team')),
            ],
            options={
                'ordering': ['sequence_order', 'team__name'],
            },
        ),
        migrations.AddField(
            model_name='resourceplanphase',
            name='plan_project_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='resource_plan.resourceplanprojectteam'),
        ),
        migrations.CreateModel(
            name='ResourcePlanAssignmentCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_allocated', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Days allocated (0–10). Rounded to nearest 0.25.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('is_auto', models.BooleanField(default=True, help_text='True = engine-generated. False = manually overridden.')),
                ('is_locked', models.BooleanField(default=False, help_text='True for past sprints (3.36) — cannot be edited.')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='resource_plan.resourceplanassignment')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_cells', to='sprints.sprint')),
            ],
            options={
                'ordering': ['sprint__start_date'],
                'unique_together': {('assignment', 'sprint')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanCapacityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_days', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_overrides', to='resource_plan.resourceplan')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_overrides', to='sprints.sprint')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_overrides', to='team_members.teammember')),
            ],
            options={
                'ordering': ['sprint__start_date', 'team_member__last_name'],
                'unique_together': {('plan', 'team_member', 'sprint')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanLeafPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(choices=[(Decimal('0.5'), '0.5 day'), (Decimal('1.0'), '1 day')], decimal_places=1, default=Decimal('1.0'), max_digits=3)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_placeholders', to='resource_plan.resourceplan')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_placeholders', to='sprints.sprint')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_placeholders', to='team_members.teammember')),
            ],
            options={
                'ordering': ['sprint__start_date', 'team_member__last_name'],
                'unique_together': {('plan', 'team_member', 'sprint')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanPhaseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('SS', 'Start to Start'), ('FS', 'Finish to Start'), ('FF', 'Finish to Finish')], max_length=2)),
                ('from_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='resource_plan.resourceplanphase')),
                ('to_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='resource_plan.resourceplanphase')),
            ],
            options={
                'unique_together': {('from_phase', 'to_phase')},
            },
        ),
        migrations.CreateModel(
            name='ResourcePlanSprintBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('plan_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_budgets', to='resource_plan.resourceplanproject')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sprint_budgets', to='sprints.sprint')),
            ],
            options={
                'ordering': ['sprint__start_date'],
                'unique_together': {('plan_project', 'sprint')},
            },
        ),
    ]
