# Generated by Django 6.0.3 on 2026-03-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_plan', '0001_initial'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePlanAssignmentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_project_level', models.BooleanField(default=False, help_text='When True, applies to all engineers on the project for this window.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='resource_plan.resourceplanassignment')),
                ('pause_from_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_pauses', to='sprints.sprint')),
                ('resume_at_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_resumes', to='sprints.sprint')),
            ],
            options={
                'ordering': ['pause_from_sprint__start_date'],
            },
        ),
    ]
